spring:
  cache:
    type: redis
  redis:
    password: str0ng_passw0rd
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    sentinel:
      master: mymaster
      nodes: spring-redis-sentinel_redis-sentinel_1:26379,spring-redis-sentinel_redis-sentinel_2:26379,spring-redis-sentinel_redis-sentinel_3:26379
server:
  port: 8088
